export type TabGroup = 'overview' | 'industry' | 'shop' | 'arena' | 'hardware' | 'software' | 'hri' | 'cli' | 'api';

export interface TabDefinition {
  id: string;
  label: string;
  group: TabGroup;
  hidden?: boolean;
}

export const TAB_GROUPS: { id: TabGroup; label: string }[] = [
  { id: 'overview', label: 'Overview' },
  { id: 'industry', label: 'Industry' },
  { id: 'shop', label: 'Shop' },
  { id: 'arena', label: 'Arena' },
  { id: 'hardware', label: 'Hardware' },
  { id: 'software', label: 'Software' },
  { id: 'hri', label: 'HRI' },
  { id: 'cli', label: 'CLI' },
  { id: 'api', label: 'API' },
];

export const TABS: TabDefinition[] = [
  { id: 'skeleton', label: 'Skeleton', group: 'overview' },
  { id: 'all_oems', label: 'All OEMs', group: 'overview' },
  { id: 'network', label: 'Network', group: 'overview' },
  { id: 'geopolitics', label: 'Geopolitics', group: 'industry' },
  { id: 'funding', label: 'Funding', group: 'industry' },
  { id: 'timeline', label: 'Buildout', group: 'industry' },
  { id: 'factories', label: 'Factories', group: 'industry' },
  { id: 'equipment', label: 'Equipment', group: 'shop' },
  { id: 'buy_data', label: 'Buy Data', group: 'shop' },
  { id: 'sell_data', label: 'Sell Data', group: 'shop' },
  { id: 'collect_data', label: 'Collect Data', group: 'shop' },
  { id: 'seller_terms', label: '', group: 'shop', hidden: true },
  { id: 'buyer_terms', label: '', group: 'shop', hidden: true },
  { id: 'collector_terms', label: '', group: 'shop', hidden: true },
  { id: 'account', label: 'Account', group: 'shop' },
  { id: 'components', label: 'Components', group: 'shop' },
  { id: 'arena_oems', label: 'Atlas Arena', group: 'arena' },
  { id: 'arena_suppliers', label: 'Supplier Arena', group: 'arena', hidden: true },
  { id: 'arena_vla', label: 'VLA Arena', group: 'arena', hidden: true },
  { id: 'arena_investment', label: 'Investment Arena', group: 'arena', hidden: true },
  { id: 'arena_components', label: 'Component Arena', group: 'arena', hidden: true },
  { id: 'arena_scenarios', label: 'Scenario Arena', group: 'arena', hidden: true },
  { id: 'sensors_general', label: 'Sensors', group: 'hardware' },
  { id: 'compute', label: 'Compute', group: 'hardware' },
  { id: 'batteries', label: 'Battery', group: 'hardware' },
  { id: 'motors', label: 'Motors', group: 'hardware' },
  { id: 'reducers', label: 'Reducers', group: 'hardware' },
  { id: 'bearings', label: 'Bearings', group: 'hardware' },
  { id: 'actuators_rotary', label: 'Actuators', group: 'hardware' },
  { id: 'screws', label: 'Screws', group: 'hardware' },
  { id: 'end_effectors', label: 'Hands', group: 'hardware' },
  { id: 'pcbs', label: 'PCBs', group: 'hardware' },
  { id: 'vlas', label: 'VLA', group: 'software' },
  { id: 'reward_models', label: 'Reward Models', group: 'software' },
  { id: 'world_models', label: 'World Models', group: 'software' },
  { id: 'sim_platforms', label: 'Sim Platforms', group: 'software' },
  { id: 'viz_tools', label: 'Viz Tools', group: 'software' },
  { id: 'displays', label: 'Displays', group: 'hri' },
  { id: 'safety_standards', label: 'Safety & Standards', group: 'hri' },
  { id: 'cli_install', label: 'Install', group: 'cli' },
  { id: 'cli_commands', label: 'Commands', group: 'cli' },
  { id: 'cli_examples', label: 'Examples', group: 'cli' },
  { id: 'api_getting_started', label: 'Getting Started', group: 'api' },
  { id: 'api_companies', label: 'Companies', group: 'api' },
  { id: 'api_supply_chain', label: 'Supply Chain', group: 'api' },
  { id: 'api_resources', label: 'Resources', group: 'api' },
  { id: 'api_ai_sim', label: 'AI & Sim', group: 'api' },
  { id: 'api_safety', label: 'Safety', group: 'api' },
  { id: 'api_query', label: 'Query', group: 'api' },
];

export const TAB_TO_PATH: Record<string, string> = {
  skeleton: '/',
  all_oems: '/oems',
  network: '/network',
  funding: '/industry/funding',
  factories: '/industry/factories',
  geopolitics: '/industry/geopolitics',
  timeline: '/industry/buildout',
  buy_data: '/data/buy',
  sell_data: '/data/sell',
  collect_data: '/data/collect',
  seller_terms: '/data/seller-terms',
  buyer_terms: '/data/buyer-terms',
  collector_terms: '/data/collector-terms',
  account: '/data/account',
  equipment: '/shop/equipment',
  components: '/shop/components',
  arena_oems: '/arena/humanoids',
  arena_suppliers: '/arena/suppliers',
  arena_vla: '/arena/vla',
  arena_investment: '/arena/investment',
  arena_components: '/arena/components',
  arena_scenarios: '/arena/scenarios',
  sensors_general: '/hardware/sensors',
  compute: '/hardware/compute',
  batteries: '/hardware/battery',
  motors: '/hardware/motors',
  reducers: '/hardware/reducers',
  bearings: '/hardware/bearings',
  actuators_rotary: '/hardware/actuators',
  screws: '/hardware/screws',
  end_effectors: '/hardware/hands',
  pcbs: '/hardware/pcbs',
  vlas: '/software/vla',
  reward_models: '/software/reward-models',
  world_models: '/software/world-models',
  sim_platforms: '/software/sim-platforms',
  viz_tools: '/software/viz-tools',
  displays: '/hri/displays',
  safety_standards: '/hri/safety-standards',
  cli_install: '/cli/install',
  cli_commands: '/cli/commands',
  cli_examples: '/cli/examples',
  api_getting_started: '/api/getting-started',
  api_companies: '/api/companies',
  api_supply_chain: '/api/supply-chain',
  api_resources: '/api/resources',
  api_ai_sim: '/api/ai-sim',
  api_safety: '/api/safety',
  api_query: '/api/query',
};

export const PATH_TO_TAB: Record<string, string> = {
  ...Object.fromEntries(
    Object.entries(TAB_TO_PATH).map(([tab, path]) => [path, tab])
  ),
  '/geopolitics': 'geopolitics',
  '/buildout': 'timeline',
  '/shop': 'equipment',
  '/shop/data': 'buy_data',
};
